"""initial schema

Revision ID: 045202897e89
Revises: 
Create Date: 2026-02-27 21:59:11.347212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '045202897e89'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_ingestions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('source_code', sa.String(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('file_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_ingestions')),
    sa.UniqueConstraint('file_hash', name=op.f('uq_file_ingestions_file_hash'))
    )
    op.create_table('source_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('file_ingestion_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('short_description', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('highlights', sa.JSON(), nullable=True),
    sa.Column('location_name', sa.String(), nullable=True),
    sa.Column('location_city', sa.String(), nullable=True),
    sa.Column('location_district', sa.String(), nullable=True),
    sa.Column('location_street', sa.String(), nullable=True),
    sa.Column('location_street_no', sa.String(), nullable=True),
    sa.Column('location_zipcode', sa.String(), nullable=True),
    sa.Column('title_normalized', sa.String(), nullable=True),
    sa.Column('short_description_normalized', sa.String(), nullable=True),
    sa.Column('location_name_normalized', sa.String(), nullable=True),
    sa.Column('location_city_normalized', sa.String(), nullable=True),
    sa.Column('blocking_keys', sa.JSON(), nullable=True),
    sa.Column('geo_latitude', sa.Float(), nullable=True),
    sa.Column('geo_longitude', sa.Float(), nullable=True),
    sa.Column('geo_confidence', sa.Float(), nullable=True),
    sa.Column('geo_country', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_code', sa.String(), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('is_family_event', sa.Boolean(), nullable=True),
    sa.Column('is_child_focused', sa.Boolean(), nullable=True),
    sa.Column('admission_free', sa.Boolean(), nullable=True),
    sa.Column('registration_required', sa.Boolean(), nullable=True),
    sa.Column('registration_contact', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('batch_index', sa.Integer(), nullable=True),
    sa.Column('extracted_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['file_ingestion_id'], ['file_ingestions.id'], name=op.f('fk_source_events_file_ingestion_id_file_ingestions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_events'))
    )
    op.create_table('event_dates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['source_events.id'], name=op.f('fk_event_dates_event_id_source_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_dates'))
    )
    op.create_index('ix_event_dates_event_id_date', 'event_dates', ['event_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_event_dates_event_id_date', table_name='event_dates')
    op.drop_table('event_dates')
    op.drop_table('source_events')
    op.drop_table('file_ingestions')
    # ### end Alembic commands ###
