"""add phase 2 tables

Revision ID: a621d57eaaf3
Revises: fb9dbc7f41c6
Create Date: 2026-02-28 08:01:51.087449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a621d57eaaf3'
down_revision: Union[str, None] = 'fb9dbc7f41c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('short_description', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('highlights', sa.JSON(), nullable=True),
    sa.Column('location_name', sa.String(), nullable=True),
    sa.Column('location_city', sa.String(), nullable=True),
    sa.Column('location_district', sa.String(), nullable=True),
    sa.Column('location_street', sa.String(), nullable=True),
    sa.Column('location_zipcode', sa.String(), nullable=True),
    sa.Column('geo_latitude', sa.Float(), nullable=True),
    sa.Column('geo_longitude', sa.Float(), nullable=True),
    sa.Column('geo_confidence', sa.Float(), nullable=True),
    sa.Column('dates', sa.JSON(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('is_family_event', sa.Boolean(), nullable=True),
    sa.Column('is_child_focused', sa.Boolean(), nullable=True),
    sa.Column('admission_free', sa.Boolean(), nullable=True),
    sa.Column('field_provenance', sa.JSON(), nullable=True),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_canonical_events'))
    )
    op.create_table('canonical_event_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('canonical_event_id', sa.Integer(), nullable=False),
    sa.Column('source_event_id', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_event_id'], ['canonical_events.id'], name=op.f('fk_canonical_event_sources_canonical_event_id_canonical_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_event_id'], ['source_events.id'], name=op.f('fk_canonical_event_sources_source_event_id_source_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_canonical_event_sources')),
    sa.UniqueConstraint('canonical_event_id', 'source_event_id', name='uq_canonical_event_sources_pair')
    )
    op.create_table('match_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_event_id_a', sa.String(), nullable=False),
    sa.Column('source_event_id_b', sa.String(), nullable=False),
    sa.Column('combined_score', sa.Float(), nullable=False),
    sa.Column('date_score', sa.Float(), nullable=False),
    sa.Column('geo_score', sa.Float(), nullable=False),
    sa.Column('title_score', sa.Float(), nullable=False),
    sa.Column('description_score', sa.Float(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("decision IN ('match', 'no_match', 'ambiguous')", name=op.f('ck_match_decisions_valid_decision')),
    sa.CheckConstraint('source_event_id_a < source_event_id_b', name=op.f('ck_match_decisions_canonical_ordering')),
    sa.ForeignKeyConstraint(['source_event_id_a'], ['source_events.id'], name=op.f('fk_match_decisions_source_event_id_a_source_events')),
    sa.ForeignKeyConstraint(['source_event_id_b'], ['source_events.id'], name=op.f('fk_match_decisions_source_event_id_b_source_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_decisions')),
    sa.UniqueConstraint('source_event_id_a', 'source_event_id_b', name='uq_match_decisions_event_pair')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_decisions')
    op.drop_table('canonical_event_sources')
    op.drop_table('canonical_events')
    # ### end Alembic commands ###
