"""add ground_truth_pairs table

Revision ID: fb9dbc7f41c6
Revises: 045202897e89
Create Date: 2026-02-27 22:17:00.857845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb9dbc7f41c6'
down_revision: Union[str, None] = '045202897e89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ground_truth_pairs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id_a', sa.String(), nullable=False),
    sa.Column('event_id_b', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('title_similarity', sa.Float(), nullable=True),
    sa.Column('labeled_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("label IN ('same', 'different')", name=op.f('ck_ground_truth_pairs_valid_label')),
    sa.CheckConstraint('event_id_a < event_id_b', name=op.f('ck_ground_truth_pairs_canonical_ordering')),
    sa.ForeignKeyConstraint(['event_id_a'], ['source_events.id'], name=op.f('fk_ground_truth_pairs_event_id_a_source_events')),
    sa.ForeignKeyConstraint(['event_id_b'], ['source_events.id'], name=op.f('fk_ground_truth_pairs_event_id_b_source_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ground_truth_pairs')),
    sa.UniqueConstraint('event_id_a', 'event_id_b', name='uq_ground_truth_pairs_event_pair')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ground_truth_pairs')
    # ### end Alembic commands ###
